### ISSUE TITLE
Suggestion: "No recipe" option

### ISSUE THREAD

**Issue by Skjolbir** [brandon-ray/foxhole-facility-planner#16]

**Comment by Skjolbir** [comment]
I want to have a light vehicle assembly station making pallets, but I do not need to know I can make 720 an hour for 18,000 bmats.
But I do want to know how many assembly materials I can make an hour.       
I'd like to show only the per hour recipe cost and production of buildings I choose.

**Comment by jimdcunningham** [comment]
Agreed. We can add a toggle to hide specific recipes in the statistics pretty easily. Might just throw a button on each recipe inside of production with an eye icon or something similar.

We have a few things in mind to give you more control over what you're producing from buildings as well, because obviously you _probably_ don't need that many material pallets haha.

**Comment by jimdcunningham** [comment]
Updated buildings so you can toggle the recipe selected inside of production. Just click the button of the recipe to toggle it on / off. Still locked to one recipe per structure though. 👍
